# Generated by Django 6.0 on 2025-12-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la Imagen'),
        ),
    ]
